site_name: Sifaka
site_url: https://sifaka-ai.github.io/sifaka/
site_description: Simple AI text improvement through research-backed critique
site_author: Evan Volgas

repo_name: sifaka-ai/sifaka
repo_url: https://github.com/sifaka-ai/sifaka
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Getting Started:
    - index.md
    - installation.md
    - getting-started/quickstart.md
  - User Guide:
    - guide/basic-usage.md
    - guide/critics.md
    - guide/validators.md
    - guide/configuration.md
    - guide/advanced-usage.md
  - Plugin Development:
    - plugin_development.md
    - plugin_api_reference.md
    - plugin_best_practices.md
  - Critics:
    - critics/overview.md
  - Architecture:
    - architecture.md
    - Design Decisions:
      - decisions/001-single-function-api.md
      - decisions/002-plugin-architecture.md
      - decisions/003-memory-management.md
      - decisions/004-error-handling.md
  - API Reference:
    - reference/api.md
  - Development:
    - development/DEVELOPER_SETUP.md
    - development/ENV_SETUP.md
  - Monitoring:
    - monitoring.md
  - About:
    - FAQ.md
    - about/license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sifaka-ai/sifaka
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sifaka/
