[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sifaka"
version = "0.4.0"
description = "Sifaka - PydanticAI-native AI validation, improvement, and evaluation framework"
authors = [{name = "Evan Volgas", email = "evan.volgas@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<3.12"
keywords = ["ai", "llm", "validation", "guardrails", "text-generation", "machine-learning"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

# Core dependencies (minimal required for basic functionality)
dependencies = [
    "pydantic>=2.11.3",
    "pydantic-ai>=0.2.0",
    "typing-extensions>=4.10.0",
    "python-dotenv>=1.0.1",
    "requests>=2.31.0",
    "httpx>=0.28.1",
    "aiofiles>=23.0.0",
    "tenacity>=8.2.3",
]

[project.optional-dependencies]
# Model providers
openai = [
    "openai>=1.82.0",
    "tiktoken>=0.9.0",
]
anthropic = [
    "anthropic>=0.50.0",
]
ollama = [
    "ollama>=0.1.0",
]
gemini = [
    "google-generativeai>=0.8.5",
]

# Retrievers and vector databases
redis = [
    "redis>=5.0.0",
]
milvus = [
    "pymilvus>=2.4.0",
]

# MCP (Model Context Protocol) support
mcp = [
    "websockets>=11.0.0",
    "jsonschema>=4.17.0",
]

# ML and classification (optional dependencies for classifiers)
classifiers = [
    "scikit-learn>=1.6.1",
    "textblob>=0.19.0",
    "langdetect>=1.0.9",
    "better-profanity>=0.7.0",
    "nltk>=3.8.1",  # Natural Language Toolkit for advanced text processing
    "spacy>=3.7.0",  # Industrial-strength NLP library
]

# Validation and guardrails (disabled due to dependency conflicts with PydanticAI)
# guardrails = [
#     "guardrails-ai>=0.5.0,<0.6.0",  # Disabled: griffe version conflict with pydantic-ai
#     "guardrails-api-client>=0.4.0a1", # Disabled: dependency of guardrails-ai
# ]

# Performance and utilities
performance = [
    "numpy>=1.26.0",
    "psutil>=5.9.5",
    "tqdm>=4.66.2",
]

# Development tools
dev = [
    "pytest>=8.0.2",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.21.0",
    "black>=24.2.0",
    "isort>=5.13.2",
    "mypy>=1.9.0",
    "ruff>=0.3.0",
    "flake8>=5.0.0",
    "autoflake>=2.0.0",
    "typer>=0.9.0",
    "pre-commit>=3.0.0",
    "ipython>=8.0.0",
    # Type stubs
    "types-aiofiles>=23.0.0",
    "types-jsonschema>=4.21.0",
    "types-PyYAML>=6.0.0",
    "types-requests>=2.31.0",
    "types-redis>=4.5.0",
    # Include all classifier dependencies for development
    "scikit-learn>=1.6.1",
    "textblob>=0.19.0",
    "langdetect>=1.0.9",
    "better-profanity>=0.7.0",
    "nltk>=3.8.1",
    "spacy>=3.7.0",
]

# Convenience groups
models = [
    "sifaka[openai,anthropic,ollama,gemini]",
]
retrievers = [
    "sifaka[redis,milvus]",
]
all = [
    "sifaka[models,retrievers,classifiers,performance,mcp]",
]
full = [
    "sifaka[all,dev]",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["sifaka*"]

[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "tests",
    "examples",
    "demos",
    "benchmarks",
    "tools",
]

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E203", "B904"]

[tool.ruff.lint.isort]
known-first-party = ["sifaka"]

[tool.pytest.ini_options]
minversion = "8.0"
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=sifaka",
    "--cov-report=term-missing",
    "--cov-report=html",
    "--cov-fail-under=80",
]
testpaths = ["tests"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
]

[tool.coverage.run]
source = ["sifaka"]
omit = [
    "*/tests/*",
    "*/examples/*",
    "*/demos/*",
    "*/__pycache__/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
disallow_subclassing_any = true
disallow_any_generics = true
exclude = ["demos/", "benchmarks/", "tools/"]

[tool.poetry]
name = "sifaka"
version = "0.4.0"
description = "Sifaka - PydanticAI-native AI validation, improvement, and evaluation framework"
authors = ["Evan Volgas <evan.volgas@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"


# Module-specific configurations

[tool.poetry.group.test.dependencies]
pytest-asyncio = "^1.0.0"
agno = "^1.5.6"
pydantic-ai = "^0.2.12"

[[tool.mypy.overrides]]
module = [
    "redis.*",
    "sklearn.*",
    "guardrails.*",
    "pymilvus.*",
    "anthropic.*",
    "openai.*",
    "numpy.*",
    "pandas.*",
    "websockets.*",
    "tiktoken.*",
    "ollama.*",
    "traitlets.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "sifaka.core.registry",
    "sifaka.core.initialize_registry",
    "sifaka.classifiers.errors",
]
follow_imports = "skip"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
