# Updated configuration for Ruff linter
line-length = 100
target-version = "py311"
select = ["E", "F", "B", "I"]
# Ignore E203 (whitespace before ':') as it conflicts with Black
# Ignore B904 (raise from) for now until we can fix all instances
ignore = ["E203", "B904"]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
]

[isort]
known-first-party = ["sifaka"]
