line-length = 100
target-version = "py38"
select = ["E", "F", "B", "I"]
ignore = ["E203"]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
]

[isort]
known-first-party = ["sifaka"]
