"""Critics for Sifaka.

This package provides critic classes that analyze and improve text generated by
language models. Critics are used in the Sifaka chain to provide feedback and
guide iterative improvement of generated content.

Available critics:
- ReflexionCritic: Uses reflection to improve text quality over time
- SelfRAGCritic: Uses retrieval-augmented generation for enhanced critique
- SelfRefineCritic: Iterative self-improvement through critique and revision
- ConstitutionalCritic: Evaluates text against constitutional principles
- PromptCritic: General-purpose critic using customizable prompts
- NCriticsCritic: Ensemble of specialized critics for comprehensive feedback

Example:
    ```python
    from sifaka.critics import (
        ReflexionCritic,
        SelfRAGCritic,
        SelfRefineCritic,
        ConstitutionalCritic,
        PromptCritic,
        NCriticsCritic,
    )
    from sifaka.core.thought import Thought

    # Create critics
    reflexion_critic = ReflexionCritic(model_name="openai:gpt-4")
    constitutional_critic = ConstitutionalCritic(
        model_name="openai:gpt-4",
        principles=["Be helpful and harmless", "Provide accurate information"]
    )

    # Create a thought with text
    thought = Thought(prompt="Explain AI", text="AI is artificial intelligence.")

    # Critique and improve
    critique_result = reflexion_critic.critique(thought)
    if critique_result["needs_improvement"]:
        improved_text = reflexion_critic.improve(thought)
        print(f"Improved text: {improved_text}")
    ```
"""

# Import base critic
from sifaka.critics.base import BaseCritic

# Import specialized critics
from sifaka.critics.reflexion import ReflexionCritic, create_reflexion_critic
from sifaka.critics.self_rag import SelfRAGCritic, create_self_rag_critic
from sifaka.critics.self_refine import SelfRefineCritic, create_self_refine_critic
from sifaka.critics.constitutional import ConstitutionalCritic, create_constitutional_critic
from sifaka.critics.prompt import PromptCritic, create_prompt_critic
from sifaka.critics.n_critics import NCriticsCritic, create_n_critics_critic

__all__ = [
    # Base critic
    "BaseCritic",
    "ReflexionCritic",
    # Specialized critics
    "SelfRAGCritic",
    "SelfRefineCritic",
    "ConstitutionalCritic",
    "PromptCritic",
    "NCriticsCritic",
    # Factory functions
    "create_reflexion_critic",
    "create_self_rag_critic",
    "create_self_refine_critic",
    "create_constitutional_critic",
    "create_prompt_critic",
    "create_n_critics_critic",
]
