name: Sifaka CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort autoflake ruff

      - name: Format code
        run: |
          isort --profile black --line-length 100 sifaka tests
          black --line-length 100 sifaka tests
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables sifaka tests
          ruff check --fix --line-length 100 sifaka tests

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: auto-format code"
          branch: ${{ github.head_ref }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: format
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install autoflake

      - name: Check formatting with Black
        run: black --check --line-length 100 sifaka tests

      - name: Check imports with isort
        run: isort --check --profile black --line-length 100 sifaka tests

      - name: Check unused imports with autoflake
        run: autoflake --check --recursive --remove-all-unused-imports --remove-unused-variables sifaka tests

      - name: Lint with Ruff
        run: ruff check --line-length 100 sifaka tests

      - name: Type check with mypy
        run: mypy sifaka

      - name: Lint with flake8
        run: flake8 sifaka tests

  lint-main:
    name: Lint Main
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install autoflake

      - name: Check formatting with Black
        run: black --check --line-length 100 sifaka tests

      - name: Check imports with isort
        run: isort --check --profile black --line-length 100 sifaka tests

      - name: Check unused imports with autoflake
        run: autoflake --check --recursive --remove-all-unused-imports --remove-unused-variables sifaka tests

      - name: Lint with Ruff
        run: ruff check --line-length 100 sifaka tests

      - name: Type check with mypy
        run: mypy sifaka

      - name: Lint with flake8
        run: flake8 sifaka tests

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,all]"

      - name: Run tests with coverage
        run: pytest --cov=sifaka --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build package
        run: python -m build

      - name: Store built package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
