name: Sifaka CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install autoflake

      - name: Check formatting with Black
        run: black --check sifaka tests

      - name: Check imports with isort
        run: isort --check sifaka tests

      - name: Check unused imports with autoflake
        run: autoflake --check --recursive --remove-all-unused-imports --remove-unused-variables sifaka tests

      - name: Lint with Ruff
        run: ruff check sifaka tests

      - name: Type check with mypy
        run: mypy sifaka

      - name: Lint with flake8
        run: flake8 sifaka tests

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,all]"

      - name: Run tests with coverage
        run: pytest --cov=sifaka --cov-report=xml --cov-report=term

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Build package
        run: python -m build

      - name: Store built package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
